name: Run automated tests on push

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    
    services:
      # Label used to access the service container
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: spring_tests
          MYSQL_USER: spring-test
          MYSQL_PASSWORD: spring-test
          MYSQL_ROOT_PASSWORD: root

        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Verify MySql connection
        run: |
            sudo apt-get install mysql-client
            mysql --host=127.0.0.1 --user=root --password=root --execute="SHOW TABLES" information_schema
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
        env:
          DB_PORT: ${{ job.services.mysql.ports[3306] }}

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
